### ISSUE TITLE
NSF: Portfolio list of companies randomized for API

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf-sbir#301]
List of companies to randomize within portfolio page - per discussion.   @kmonterr is that a list we could get from you?  Or is there a particular subset we should focus on?

**Comment by OpenGlobe** [comment]
Hi @kmonterr - just following up on this issue - do we have any further guidance on how to handle the list of companies on the portfolio pages?  Per Brian's note, I think we'd need a curated list of companies to randomize the results from.   Or, if I'm reading Brian's note correctly, we could randomize from all companies that the API is reporting. 

cc: @gemfarmer

**Comment by gemfarmer** [comment]
@OpenGlobe @kmonterr I'll try to clarify here. I'm advocating for creating a curated list of companies that we could use to create randomized subsets.

Steps:
1. Create list of _potential_ companies to choose from. Let's say 400 companies.
2. Use the list of companies to query the API and create a flat file that includes awards from all 400 companies.
3. When someone hits the page, we **randomly** select a subset of those companies (let's say 50) and display those in a **random** order.
4. You refresh and you get a new set of 50 companies drawn from the list of 400.

**Comment by kmonterr** [comment]
Hi @gemfarmer I just got this list of our Program Directors topic areas since December 2013. Is it what you need?
Henry Ahn (6-2017) “’Biomedical Technologies” (BM); (12-2016) (BM) and “Smart Health” (SH).

Peter Atherton (6-2017) “Informational Technologies” (IT); (12-2016) (IT); (6-2016) ( IT); (12-2015) (IT); (6-2015) (IT); (12-2014) (IC); (6-2014) (IC); (12-2013) “Information and Communication Technologies”  (IC).

Anna Brady-Estevez (6-2017)  “Chemical and Environmental Technologies” (CT); (12-2016) “Environmental Technologies” (EY)

Prakash Balan (12-2016) “Chemical Technologies” (CT); (6-2016) (CT); (12-2015) (CT); (6-2015) (CT); (12-2014) (CT); (6-2014) (CT); (12-2013) (CT); (6-2013) “Biological & Chemical Technologies” (BC) Prakash is no longer an SBIR PD.

Steve Konsek (6-2016) “Semiconductors (S), Photonics (PH), Internet Of Things (IoT)”; (12-2015) (S,PH, and IoT); (6-2015) (S, PH. and  IoT); (12-2014) (S and PH); (6-2014) (S and PH); (12-2013) (S and PH); (6-2013) (S and PH))  Steve is no longer an SBIR PD.

Glenn Larsen (6-2017) “Educational Technologies and Applications” (EA); (12-2016) (EA); (6-2016h) (EA); (12-2015) (EA); (6-2015) (EA); (12-2014) (EA); (6-2014) (EA); (12-2013) (EA); (6-2013) (EA)

Debasis Majumdar (6-2017) ”Advanced Material and Instrumentation (MI); (12-2016) (MI)

Rajesh Mehta (6-2017) “Advanced Manufacturing and Nanotechnologies (MN); (12-2016) (MN); (6-2016) (MN); (12-2015) (MN); (6-2015) (MN); (12-2014) (MN); (6-2014) (MN); (12-2013) (MN); (6-2013) (MN).

Murali Nair (6-2017) “Electronics, Hardware, Robotics and Wireless Technologies” (EW); (12-2016) (EW); (6-2016) (EW); (12-2015) (EW); (6-2015) (EW); (12-2014) (EW); (6-2014) (EW); (12-2013) (EW); (6-2013) (EW).

Ben Schrag (6-2017) “Other Topics” (OT); (12-2016) (OT); (6-2016) “Advanced Materials and Instrumentation” (MI); (12-2015) (MI); (6-2015) (MI); (12-2014) (MI); (6-2014) (MI); (12-2013) (MI); (6-2013) (MI).

Rich Schwerdtferger (6-2017) “Internet of Things (IoT), Semiconductors (S), and Photonic (PH) Devices; (12-2016) (IoT) and PH).

Ruth Schuman (6-2017) “Biological Technologies’ (BT); (12-2016) (BT); (6-2016) (BT); (12-2016) (BT); (6-2016) (BT); (12-2015) (BT); (6-2015) (BT); (12-2014) (BT); (6-2013) (BT); (12-2013) BT).

Jesus Soriano (6-2017) “Smart Health (SH) and Biomedical Technologies (BM); (12-2016) (SH and BM); (6-2016) (SH and BT); (12-2015) (SM and BT); (6-2014) (SH and BT); (12-2013) (SH and BT); (6-2013) (SH and BT).

**Comment by gemfarmer** [comment]
@kmonterr this is great! A few questions: 
- Do the dates indicate the month that they started as the PO of that topic? 
- Should I use the first of the month (e.g. 6/1/2016) for the API query?
- Do we want to show POs (or topics) that are no longer around?

**Comment by gemfarmer** [comment]
@kmonterr 
So I'm going to do the following:
- generate portfolio data by querying for specific POs within specific time frames.
- we can reduce the size of this list by only including companies that we want to show? (or are we just showing all companies?)
- then, with this culled dataset, we will display a random subset of companies.

Is there anything I'm missing here? Do we need a separate whitelist of allowable companies, or are we ok using the list that the API generates from the information you provided above?

**Comment by kmonterr** [comment]
@gemfarmer I'm getting feedback from management now....will keep you posted in the next hour or so!

**Comment by gemfarmer** [comment]
@kmonterr 
> Neither! We included people and topics that are no longer around because they have either been merged into other topics or have been taken over by a new PD. let me know if you'd like me to reorder this to make it more digestible.

Gotcha! That makes a lot more sense now :) Thanks for clearing that up

**Comment by gemfarmer** [comment]
Questions:
> Jesus Soriano (6-2017) “Smart Health (SH) and Biomedical Technologies (BM); (12-2016) (SH and BM); (6-2016) (SH and BT); (12-2015) (SM and BT); (6-2014) (SH and BT); (12-2013) (SH and BT); (6-2013) (SH and BT).
- It looks like Jesus has SH, BM, and BT. Is that correct? Or is he only in Smart Health and Bio**medical** Technologies?

**Comment by kmonterr** [comment]
He had SH, BM and BT. He now has SH primarily, and Henry Ahn has BM primarily. I hope that helps!

**Comment by gemfarmer** [comment]
@kmonterr that does help, but as I look at this a bit more, given how much these PDs are overlapping on topics and time periods, I'm confused about how we can successfully determine which topic area an awardee belongs to based off the PD. Is there a primary that we can use to infer that from? Also, most of the touch ones to determine are relating to Jesus Soriano.

**Comment by kmonterr** [comment]
@gemfarmer I'll try to help you with this first thing in the morning!

**Comment by gemfarmer** [comment]
@kmonterr cool. I've taken the list that you made and broken it apart by topic area. 

```yml
TopicAccronym: #
  show_topic: true # "true" indicates that we will show it on the portfolio section of the site
  project_directors:
    - name: Director Name
      time_start: 06/01/2017 # API date_start
      time_end: current # API date_end. For instance"06/01/2017" would indicate that their last session started 12/01/206
      ...

BM:
  show_topic: true
  project_directors:
    - name: Henry Ahn
      time_start: 06/01/2017
      time_end: current 
      ...
    - name: Jesus Soriano
      time_start: 12/01/2016
      time_end: current
      ...
SH:
  show_topic: true
  project_directors:
    - name: Henry Ahn
      time_start: 12/01/2016
      time_end: 06/01/2017
      ...
    - name: Jesus Soriano
      time_start: 06/01/2013
      time_end: current
      ...

IT:
  show_topic: true
  project_directors:
    - name: Peter Atherton
      time_start: 06/01/2015
      time_end: current
      ...

IC:
  show_topic: false
  project_directors:
    - name: Peter Atherton
      time_start: 12/01/2013
      time_end: 06/01/2015
      ...

CT:
  show_topic: true
  project_directors:
    - name: Anna Brady-Estevez
      time_start: 06/01/2017
      time_end: current
      ...
    - name: Prakash Balan
      time_start: 12/01/2013
      time_end: 06/01/2017
      ...

ET:
  show_topic: false
  project_directors:
    - name: Anna Brady-Estevez
      time_start: 12/01/2016
      time_end: 06/01/2017
      ...

EA:
  show_topic: true
  project_directors:
    - name: Glenn Larsen
      time_start: 06/01/2013
      time_end: current
      ...

MI:
  show_topic: true
  project_directors:
    - name: Debasis Majumdar
      time_start: 12/01/2016
      time_end: current
      ...
    - name: Ben Schrag
      time_start: 06/01/2013
      time_end: 12/01/2016
      ...

MN:
  show_topic: true
  project_directors:
    - name: Rajesh Mehta
      time_start: 06/01/2013
      time_end: current
      ...

EW:
  show_topic: true
  project_directors:
    - name: Murali Nair
      time_start: 06/01/2013
      time_end: current
      ...

OT:
  show_topic: true
  project_directors:
    - name: Ben Schrag
      time_start: 12/01/2016
      time_end: current
      ...

IoT:
  show_topic: true
  project_directors:
    - name: Rich Schwerdtferger
      time_start: 12/01/2016
      time_end: current
      ...
    - name: Steve Konsek
      time_start: 06/01/2015
      time_end: 12/01/2016
      ...

BT:
  show_topic: true
  project_directors:
    - name: Ruth Schuman
      time_start: 06/01/2013
      time_end: current
    - name: Jesus Soriano
      time_start: 12/01/2016
      time_end: current

S and PH:
  show_topic: true
  - name: Rich Schwerdtferger
      time_start: 12/01/2016
      time_end: current
      ...
  - name: Rich Schwerdtferger
      time_start: 06/01/2013
      time_end: 12/01/2016
      ...
```
